# Generated by Django 5.0.6 on 2024-05-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateField(null=True),
        ),
    ]
