# Generated by Django 5.0.6 on 2024-05-18 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Tasks", "0002_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
